"""Level editing values, views, and conversion outputs."""

from ._core import (
    AnchorFlag,
    DegenerateFacePolicy,
    Level,
    LevelAnchor as Anchor,
    LevelAnchorCollection as AnchorCollection,
    LevelAnchorConnection as AnchorConnection,
    LevelAnchorConnectionCollection as AnchorConnectionCollection,
    LevelAnchorConnectionRef as AnchorConnectionRef,
    LevelAnchorRef as AnchorRef,
    LevelBytesOutput as BytesOutput,
    LevelCorner as Corner,
    LevelEntity as Entity,
    LevelEntityCollection as EntityCollection,
    LevelEntityRef as EntityRef,
    LevelFace as Face,
    LevelFaceCollection as FaceCollection,
    LevelFaceCornerCollection as FaceCornerCollection,
    LevelFaceCornerRef as FaceCornerRef,
    LevelFaceCornerVertexRef as FaceCornerVertexRef,
    LevelFaceRef as FaceRef,
    LevelFog as Fog,
    LevelFogCollection as FogCollection,
    LevelFogRef as FogRef,
    LevelGlbImportInfo as GlbImportInfo,
    LevelGlbOutput as GlbOutput,
    LevelImport as Import,
    LevelLight as Light,
    LevelLightCollection as LightCollection,
    LevelLightRef as LightRef,
    LightFlag,
    LevelLoadingScreenRef as LoadingScreenRef,
    LevelMesh as Mesh,
    LevelMinimap as Minimap,
    LevelMinimapRef as MinimapRef,
    LevelModelPreviewReport as ModelPreviewReport,
    LevelNativeOutput as NativeOutput,
    LevelNavSurfaceInfo as NavSurfaceInfo,
    LevelNavSurface as NavSurface,
    LevelNavSurfaceTriangle as NavSurfaceTriangle,
    LevelNavTriangleCollection as NavTriangleCollection,
    LevelNavTriangleRef as NavTriangleRef,
    LevelNavVertexCollection as NavVertexCollection,
    LevelNavVertexRef as NavVertexRef,
    LevelPath as Path,
    LevelPathCollection as PathCollection,
    LevelPathNode as PathNode,
    LevelPathNodeCollection as PathNodeCollection,
    LevelPathNodeRef as PathNodeRef,
    LevelPathRef as PathRef,
    LevelPlayerSpawn as PlayerSpawn,
    LevelPlayerSpawnRef as PlayerSpawnRef,
    LevelPortal as Portal,
    LevelPortalCollection as PortalCollection,
    LevelPortalRef as PortalRef,
    LevelRoom as Room,
    LevelRoomCollection as RoomCollection,
    LevelRoomDistance as RoomDistance,
    LevelRoomDistanceCollection as RoomDistanceCollection,
    LevelRoomDistanceRef as RoomDistanceRef,
    LevelRoomRef as RoomRef,
    LevelRenderedMinimap as RenderedMinimap,
    LevelTextureCollection as TextureCollection,
    LevelTextureRef as TextureRef,
    LevelVertex as Vertex,
    LevelVertexCollection as VertexCollection,
    LevelVertexRef as VertexRef,
    LevelZone as Zone,
    LevelZoneAmbiance as ZoneAmbiance,
    LevelZoneCollection as ZoneCollection,
    LevelZoneRef as ZoneRef,
    MinimapSampler,
    MinimapRenderMode,
    LoadingScreenLayout,
    PathNodeType,
    PortalShape,
    PositionWeldMetric,
    ZoneHeightMode,
    level_mini_offset_from_projection_offset as mini_offset_from_projection_offset,
    level_projection_offset_for_level as projection_offset_for_level,
    level_projection_offset_from_mini_offset as projection_offset_from_mini_offset,
)
from ._facade import install_immutable_values as _install_immutable_values
from ._facade import install_record_semantics as _install_record_semantics
from ._facade import install_record_repr as _install_record_repr
from ._facade import publish_types as _publish_types

__all__ = [
    "Anchor",
    "AnchorCollection",
    "AnchorConnection",
    "AnchorConnectionCollection",
    "AnchorConnectionRef",
    "AnchorFlag",
    "AnchorRef",
    "BytesOutput",
    "Corner",
    "DegenerateFacePolicy",
    "Entity",
    "EntityCollection",
    "EntityRef",
    "Face",
    "FaceCollection",
    "FaceCornerCollection",
    "FaceCornerRef",
    "FaceCornerVertexRef",
    "FaceRef",
    "Fog",
    "FogCollection",
    "FogRef",
    "GlbImportInfo",
    "GlbOutput",
    "Import",
    "Level",
    "Light",
    "LightCollection",
    "LightRef",
    "LightFlag",
    "LoadingScreenLayout",
    "LoadingScreenRef",
    "Minimap",
    "MinimapRef",
    "MinimapRenderMode",
    "MinimapSampler",
    "Mesh",
    "ModelPreviewReport",
    "NativeOutput",
    "NavSurfaceInfo",
    "NavSurface",
    "NavSurfaceTriangle",
    "NavTriangleCollection",
    "NavTriangleRef",
    "NavVertexCollection",
    "NavVertexRef",
    "Path",
    "PathCollection",
    "PathNode",
    "PathNodeCollection",
    "PathNodeRef",
    "PathNodeType",
    "PathRef",
    "PlayerSpawn",
    "PlayerSpawnRef",
    "Portal",
    "PortalCollection",
    "PortalRef",
    "PortalShape",
    "PositionWeldMetric",
    "Room",
    "RoomCollection",
    "RoomDistance",
    "RoomDistanceCollection",
    "RoomDistanceRef",
    "RoomRef",
    "RenderedMinimap",
    "TextureCollection",
    "TextureRef",
    "Vertex",
    "VertexCollection",
    "VertexRef",
    "Zone",
    "ZoneAmbiance",
    "ZoneCollection",
    "ZoneHeightMode",
    "ZoneRef",
    "mini_offset_from_projection_offset",
    "projection_offset_for_level",
    "projection_offset_from_mini_offset",
]

_publish_types(globals(), __name__, __all__)
_install_immutable_values(
    globals(),
    (
        "BytesOutput",
        "GlbImportInfo",
        "GlbOutput",
        "Import",
        "Minimap",
        "ModelPreviewReport",
        "NativeOutput",
        "NavSurfaceInfo",
        "PlayerSpawn",
        "RenderedMinimap",
        "ZoneAmbiance",
    ),
)
_install_record_semantics(
    globals(),
    {
        "GlbImportInfo": ("applied_arx_offset",),
        "NavSurfaceInfo": ("has_surface", "vertex_count", "triangle_count"),
        "ModelPreviewReport": (
            "mapped_models",
            "previewed_entities",
            "skipped_anonymous_models",
            "skipped_unmappable_models",
            "skipped_duplicate_models",
            "skipped_invalid_models",
        ),
        "MinimapSampler": ("encoded_image", "color"),
        "Vertex": ("position",),
        "Corner": ("vertex", "normal", "u", "v", "color"),
        "Face": ("corners", "texture", "room", "flags", "transval"),
        "RoomDistance": ("distance", "portal_a", "portal_b"),
        "AnchorConnection": ("first", "second"),
        "NavSurfaceTriangle": ("vertices",),
        "PathNode": ("relative_position", "type", "time_ms"),
        "Room": ("name",),
        "Portal": ("name", "room_1", "room_2", "shape", "vertices"),
        "Anchor": ("position", "radius", "height", "flags", "name"),
        "Light": ("name", "position", "color", "fall_start", "fall_end", "intensity", "flicker", "effect_radius", "effect_frequency", "effect_size", "effect_speed", "flare_size", "flags"),
        "Entity": ("class_path", "ident", "position", "rotation", "name"),
        "Fog": ("position", "color", "size", "directional", "scale", "rotation", "speed", "rotate_speed", "lifetime_ms", "frequency", "name"),
        "Zone": ("name", "perimeter_xz", "reference_y", "height_mode", "height", "color", "far_clip", "ambiance"),
        "Path": ("name", "position", "nodes"),
        "Minimap": ("encoded_image", "world_xz_bounds"),
        "RenderedMinimap": ("projection_offset", "encoded_image"),
    },
    {
        "MinimapSampler": ("encoded_image",),
        "Minimap": ("encoded_image",),
        "RenderedMinimap": ("encoded_image",),
    },
)
_install_record_repr(
    globals(),
    {
        "NativeOutput": ("texture_files",),
        "BytesOutput": ("texture_files",),
        "Import": ("texture_source_paths", "glb_info"),
        "GlbOutput": ("model_preview_report",),
    },
)
