"""Model editing values, views, and conversion outputs."""

from ._core import (
    DegenerateFacePolicy,
    ImageFormat,
    InventoryIcon,
    InventoryIconLayout,
    ModelInventoryIconRef as InventoryIconRef,
    Model,
    ModelActionPoint as ActionPoint,
    ModelActionPointCollection as ActionPointCollection,
    ModelActionPointRef as ActionPointRef,
    ModelBone as Bone,
    ModelBoneCollection as BoneCollection,
    ModelBoneRef as BoneRef,
    ModelBytesOutput as BytesOutput,
    ModelCorner as Corner,
    ModelFace as Face,
    ModelFaceCollection as FaceCollection,
    ModelFaceCornerCollection as FaceCornerCollection,
    ModelFaceCornerRef as FaceCornerRef,
    ModelFaceCornerVertexRef as FaceCornerVertexRef,
    ModelFaceCornerVertexSelectionSet as FaceCornerVertexSelectionSet,
    ModelFaceRef as FaceRef,
    ModelGlbOutput as GlbOutput,
    ModelImport as Import,
    ModelNativeOutput as NativeOutput,
    ModelOrigin as Origin,
    ModelOriginRef as OriginRef,
    ModelSelection as Selection,
    ModelSelectionCollection as SelectionCollection,
    ModelSelectionLeadingVertex as SelectionLeadingVertex,
    ModelSelectionLeadingVertexRef as SelectionLeadingVertexRef,
    ModelSelectionRef as SelectionRef,
    ModelSelectionSet as SelectionSet,
    ModelSelectionValueSet as SelectionValueSet,
    ModelSkeleton as Skeleton,
    ModelTextureCollection as TextureCollection,
    ModelTextureRef as TextureRef,
    ModelVertex as Vertex,
    ModelVertexCollection as VertexCollection,
    ModelVertexRef as VertexRef,
    ObjMaterialLibrary,
    ObjOutput,
    PositionWeldMetric,
    obj_material_library_paths,
)
from ._facade import install_immutable_values as _install_immutable_values
from ._facade import install_record_semantics as _install_record_semantics
from ._facade import install_record_repr as _install_record_repr
from ._facade import publish_types as _publish_types

__all__ = [
    "ActionPoint",
    "ActionPointCollection",
    "ActionPointRef",
    "Bone",
    "BoneCollection",
    "BoneRef",
    "BytesOutput",
    "Corner",
    "DegenerateFacePolicy",
    "Face",
    "FaceCollection",
    "FaceCornerCollection",
    "FaceCornerRef",
    "FaceCornerVertexRef",
    "FaceCornerVertexSelectionSet",
    "FaceRef",
    "GlbOutput",
    "ImageFormat",
    "Import",
    "InventoryIcon",
    "InventoryIconLayout",
    "InventoryIconRef",
    "Model",
    "NativeOutput",
    "ObjMaterialLibrary",
    "ObjOutput",
    "Origin",
    "OriginRef",
    "PositionWeldMetric",
    "Selection",
    "SelectionCollection",
    "SelectionLeadingVertex",
    "SelectionLeadingVertexRef",
    "SelectionRef",
    "SelectionSet",
    "SelectionValueSet",
    "Skeleton",
    "TextureCollection",
    "TextureRef",
    "Vertex",
    "VertexCollection",
    "VertexRef",
    "obj_material_library_paths",
]

_publish_types(globals(), __name__, __all__)
_install_immutable_values(
    globals(),
    (
        "BytesOutput",
        "GlbOutput",
        "Import",
        "InventoryIcon",
        "NativeOutput",
        "ObjOutput",
        "Selection",
    ),
)
_install_record_semantics(
    globals(),
    {
        "Vertex": ("position", "bone", "selections"),
        "Corner": ("vertex", "normal", "u", "v"),
        "Face": ("corners", "normal", "texture", "flags", "transval"),
        "Bone": ("name", "position", "parent", "blob_shadow_size", "selections"),
        "ActionPoint": ("name", "position", "bone", "selections"),
        "Origin": ("bone", "selections"),
        "SelectionLeadingVertex": ("position", "bone"),
        "ObjMaterialLibrary": ("path", "text"),
        "InventoryIcon": ("encoded_image", "width_slots", "height_slots"),
    },
    {"InventoryIcon": ("encoded_image",)},
)
_install_record_repr(
    globals(),
    {
        "NativeOutput": ("texture_files",),
        "BytesOutput": ("texture_files",),
        "Import": (
            "animations",
            "texture_source_paths",
            "sound_sources",
            "animation_report",
        ),
        "GlbOutput": ("sound_files", "animation_report"),
        "ObjOutput": ("texture_files",),
    },
)
