from enum import Enum, StrEnum
from typing import overload

class ModelType(StrEnum):
    NPC: ModelType
    FIX_INTER: ModelType
    SYSTEM: ModelType
    ARMOR: ModelType
    JEWELRY: ModelType
    MAGIC: ModelType
    MOVABLE: ModelType
    PROVISIONS: ModelType
    QUEST_ITEM: ModelType
    SPECIAL: ModelType
    WEAPONS: ModelType
    UI_RUNES: ModelType
    UI_MENUS: ModelType
    EDITOR: ModelType

class AnimationType(StrEnum):
    NPC: AnimationType
    FIX_INTER: AnimationType

class ResourceKind(Enum):
    NONE: ResourceKind
    LEVEL: ResourceKind
    MODEL: ResourceKind
    ANIMATION: ResourceKind
    CINEMATIC: ResourceKind
    AMBIANCE: ResourceKind

class EntityClassKind(Enum):
    UNKNOWN: EntityClassKind
    ITEM: EntityClassKind
    NPC: EntityClassKind
    FIX: EntityClassKind
    CAMERA: EntityClassKind
    MARKER: EntityClassKind

class ModelPath:
    def __init__(self, type: ModelType, name: str, tweak: str = "") -> None: ...
    type: ModelType
    name: str
    tweak: str

class AnimationPath:
    def __init__(self, type: AnimationType, name: str) -> None: ...
    type: AnimationType
    name: str

class CinematicPath:
    def __init__(self, name: str) -> None: ...
    name: str

class AmbiancePath:
    def __init__(self, name: str) -> None: ...
    name: str

class SearchLocation:
    @property
    def base_path(self) -> str: ...
    @property
    def max_discovery_depth(self) -> int: ...

def resource_selector_kind(selector: str) -> ResourceKind: ...
def is_portable_filename(filename: str) -> bool: ...
def sanitize_portable_filename(filename: str) -> str: ...
def is_portable_resource_path_component(component: str) -> bool: ...
def texture_directory() -> str: ...
def sound_directory() -> str: ...
def ambiance_sound_directory() -> str: ...
def normalize_zone_ambiance(path: str) -> str: ...
def amb_from_zone_ambiance(path: str) -> str: ...

def level_dlf(level: int) -> str: ...
def level_llf(level: int) -> str: ...
def level_fts(level: int) -> str: ...
def minimap_resource_level(level: int) -> int: ...
def level_minimap(level: int) -> str: ...
def level_loading_screen(level: int) -> str: ...
def minimap_offsets_file() -> str: ...
def level_from_dlf(path: str) -> int: ...
def level_from_llf(path: str) -> int: ...
def level_from_fts(path: str) -> int: ...
def dlf_scene_from_level_name(name: str) -> str: ...
def level_selector(level: int) -> str: ...
def level_from_selector(selector: str) -> int: ...
def fts_from_dlf_scene(path: str) -> str: ...

def model_ftl(model: ModelPath) -> str: ...
def model_from_ftl(path: str) -> ModelPath: ...
def entity_class_from_ftl(path: str) -> str: ...
def ftl_from_entity_class(path: str) -> str: ...
def entity_class_kind(path: str) -> EntityClassKind: ...
def item_icon_from_entity_class(path: str) -> str | None: ...
def entity_class_from_model(model: ModelPath) -> str: ...
def base_entity_class_from_model(model: ModelPath) -> str: ...
def model_from_entity_class(path: str) -> ModelPath: ...
def model_selector(model: ModelPath) -> str: ...
def model_from_selector(selector: str) -> ModelPath: ...

@overload
def animation_directory(type: ModelType) -> str: ...
@overload
def animation_directory(type: AnimationType) -> str: ...
def animation_tea(animation: AnimationPath) -> str: ...
def animation_from_tea(path: str) -> AnimationPath: ...
def animation_selector(animation: AnimationPath) -> str: ...
def animation_from_selector(selector: str) -> AnimationPath: ...

def cinematic_illustration_directory() -> str: ...
def cinematic_cin(cinematic: CinematicPath) -> str: ...
def cinematic_from_cin(path: str) -> CinematicPath: ...
def cinematic_selector(cinematic: CinematicPath) -> str: ...
def cinematic_from_selector(selector: str) -> CinematicPath: ...

def ambiance_amb(ambiance: AmbiancePath) -> str: ...
def ambiance_from_amb(path: str) -> AmbiancePath: ...
def ambiance_selector(ambiance: AmbiancePath) -> str: ...
def ambiance_from_selector(selector: str) -> AmbiancePath: ...

def model_search_location(type: ModelType) -> SearchLocation: ...
def animation_search_location(type: AnimationType) -> SearchLocation: ...
def level_search_location() -> SearchLocation: ...
def cinematic_search_location() -> SearchLocation: ...
def ambiance_search_location() -> SearchLocation: ...
