from enum import Enum, StrEnum
from os import PathLike
from typing import TypeAlias, overload

class ModelType(StrEnum):
    NPC: ModelType
    FIX_INTER: ModelType
    SYSTEM: ModelType
    ARMOR: ModelType
    JEWELRY: ModelType
    MAGIC: ModelType
    MOVABLE: ModelType
    PROVISIONS: ModelType
    QUEST_ITEM: ModelType
    SPECIAL: ModelType
    WEAPONS: ModelType
    UI_RUNES: ModelType
    UI_MENUS: ModelType
    EDITOR: ModelType

class AnimationType(StrEnum):
    NPC: AnimationType
    FIX_INTER: AnimationType

class ResourceKind(Enum):
    LEVEL: ResourceKind
    MODEL: ResourceKind
    ANIMATION: ResourceKind
    CINEMATIC: ResourceKind
    AMBIANCE: ResourceKind

class EntityClassKind(Enum):
    UNKNOWN: EntityClassKind
    ITEM: EntityClassKind
    NPC: EntityClassKind
    FIX: EntityClassKind
    CAMERA: EntityClassKind
    MARKER: EntityClassKind

class ModelSelector:
    """A validated, immutable Model resource identity."""
    def __init__(self, type: ModelType, name: str, tweak: str = "") -> None: ...
    @property
    def type(self) -> ModelType: ...
    @property
    def name(self) -> str: ...
    @property
    def tweak(self) -> str: ...
    @property
    def kind(self) -> ResourceKind: ...
    def __str__(self) -> str: ...
    def to_path(self) -> str: ...
    @staticmethod
    def parse(selector: str) -> ModelSelector: ...
    @staticmethod
    def from_path(path: str | PathLike[str]) -> ModelSelector: ...

class AnimationSelector:
    """A validated, immutable Animation resource identity."""
    def __init__(self, type: AnimationType, name: str) -> None: ...
    @property
    def type(self) -> AnimationType: ...
    @property
    def name(self) -> str: ...
    @property
    def kind(self) -> ResourceKind: ...
    def __str__(self) -> str: ...
    def to_path(self) -> str: ...
    @staticmethod
    def parse(selector: str) -> AnimationSelector: ...
    @staticmethod
    def from_path(path: str | PathLike[str]) -> AnimationSelector: ...

class LevelSelector:
    """A Level identity whose canonical path is its primary DLF."""
    def __init__(self, level: int) -> None: ...
    @property
    def level(self) -> int: ...
    @property
    def kind(self) -> ResourceKind: ...
    def __str__(self) -> str: ...
    def to_path(self) -> str: ...
    def associated_llf(self) -> str: ...
    def associated_fts(self) -> str: ...
    @staticmethod
    def parse(selector: str) -> LevelSelector: ...
    @staticmethod
    def from_path(path: str | PathLike[str]) -> LevelSelector: ...

class CinematicSelector:
    """A validated, immutable Cinematic resource identity."""
    def __init__(self, name: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def kind(self) -> ResourceKind: ...
    def __str__(self) -> str: ...
    def to_path(self) -> str: ...
    @staticmethod
    def parse(selector: str) -> CinematicSelector: ...
    @staticmethod
    def from_path(path: str | PathLike[str]) -> CinematicSelector: ...

class AmbianceSelector:
    """A validated, immutable Ambiance resource identity."""
    def __init__(self, name: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def kind(self) -> ResourceKind: ...
    def __str__(self) -> str: ...
    def to_path(self) -> str: ...
    @staticmethod
    def parse(selector: str) -> AmbianceSelector: ...
    @staticmethod
    def from_path(path: str | PathLike[str]) -> AmbianceSelector: ...

ResourceSelector: TypeAlias = (
    ModelSelector | AnimationSelector | LevelSelector | CinematicSelector | AmbianceSelector
)

class SearchLocation:
    @property
    def base_path(self) -> str: ...
    @property
    def max_discovery_depth(self) -> int: ...

def selector_from_string(selector: str) -> ResourceSelector:
    """Parse a selector string and return its concrete selector type."""
    ...
def selector_from_path(path: str | PathLike[str]) -> ResourceSelector:
    """Parse a canonical primary resource path and return its concrete selector type."""
    ...
def is_portable_filename(filename: str) -> bool: ...
def sanitize_portable_filename(filename: str) -> str: ...
def is_portable_resource_path_component(component: str) -> bool: ...
def texture_directory() -> str: ...
def sound_directory() -> str: ...
def ambiance_sound_directory() -> str: ...
def normalize_zone_ambiance(path: str) -> str: ...
def amb_from_zone_ambiance(path: str) -> str: ...

def minimap_resource_level(level: int) -> int: ...
def level_minimap(level: int) -> str: ...
def level_loading_screen(level: int) -> str: ...
def minimap_offsets_file() -> str: ...
def dlf_scene_from_level_name(name: str) -> str: ...
def fts_from_dlf_scene(path: str) -> str: ...

def entity_class_from_ftl(path: str) -> str: ...
def ftl_from_entity_class(path: str) -> str: ...
def entity_class_kind(path: str) -> EntityClassKind: ...
def item_icon_from_entity_class(path: str) -> str | None: ...
def entity_class_from_model(model: ModelSelector) -> str: ...
def base_entity_class_from_model(model: ModelSelector) -> str: ...
def model_from_entity_class(path: str) -> ModelSelector: ...

@overload
def animation_directory(type: ModelType) -> str: ...
@overload
def animation_directory(type: AnimationType) -> str: ...
def cinematic_illustration_directory() -> str: ...

def model_search_location(type: ModelType) -> SearchLocation: ...
def animation_search_location(type: AnimationType) -> SearchLocation: ...
def level_search_location() -> SearchLocation: ...
def cinematic_search_location() -> SearchLocation: ...
def ambiance_search_location() -> SearchLocation: ...
