// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Merxtef

#pragma once

#include <cstdint>

namespace cli {

enum class DiagnosticCode : std::uint8_t {
  kKindAmbiguous,
  kKindInvalid,
  kLogLevelAmbiguous,
  kLogLevelInvalid,
  kMissingValues,
  kInvalidNumber,
  kScaleInvalid,
  kMissingArgument,
  kInvalidMode,
  kKindConflict,
  kAmbiguousOption,
  kUnknownOption,
  kDuplicateModule,
  kModuleImplicationConflict,
  kModuleImplicationInvalid,
  kMissingInputOutput,
  kIncompatibleModules,
  kMissingDependency,
  kOutputConverterConflict,
  kInvalidModuleValue,
  kUnsupportedOutputFormat,
  kAmbiguousOutputFormat,
  kModuleOutputMismatch,
  kModuleFormatMismatch,
  kRouteConstraintConflict,
  kRouteInputMismatch,
  kRouteInvocationInvalid,
  kNoRoute,
  kAmbiguousRoute,
  kClassificationFailed,
  kResourceSelectorInvalid,
  kResourcePathInvalid,
  kResourceNotFound,
  kResourceReadFailed,
  kResourceInputInvalid,
  kResourceOutputInvalid,
  kResourceOutputCollision,
  kHelpTopicAmbiguous,
  kLevelUnsupportedInput,
  kLevelInputFailed,
  kLevelModuleFailed,
  kLevelOutputFailed,
  kLevelUnsupportedOutput,
  kDefaultGameRootUnavailable,
  kIoPathInvalid,
  kIoStatFailed,
  kIoFileTooLarge,
  kIoAllocationFailed,
  kIoOpenFailed,
  kIoReadFailed,
  kIoCreateFailed,
  kIoWriteFailed,
  kModelModuleInvalid,
  kModelModuleFailed,
  kModelUnsupportedExtra,
  kModelInputFailed,
  kModelOutputFailed,
  kModelUnsupportedInput,
  kModelUnsupportedOutput,
  kAnimationModuleFailed,
  kAnimationInputFailed,
  kAnimationOutputFailed,
  kAnimationUnsupportedInput,
  kAnimationUnsupportedOutput,
  kAmbianceModuleFailed,
  kAmbianceInputFailed,
  kAmbianceOutputFailed,
  kAmbianceUnsupportedInput,
  kAmbianceUnsupportedOutput,
  kCinematicInputFailed,
  kCinematicOutputFailed,
  kCinematicUnsupportedInput,
  kCinematicUnsupportedOutput,
  kUnhandledException,
};

const char* diagnosticCodeName(DiagnosticCode code) noexcept;
void diagnosticPrefix(DiagnosticCode code);
void diagnostic(DiagnosticCode code, const char* fmt, ...);

}  // namespace cli
