// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Merxtef

#ifndef ARX_PISTORIS_PATHS_TYPES_H
#define ARX_PISTORIS_PATHS_TYPES_H

#include <stdint.h>

// NOLINTBEGIN(readability-identifier-naming, performance-enum-size)

typedef uint8_t ArxResourceKind;
enum {
  ARX_RESOURCE_KIND_NONE = 0,
  ARX_RESOURCE_KIND_LEVEL = 1,
  ARX_RESOURCE_KIND_MODEL = 2,
  ARX_RESOURCE_KIND_ANIMATION = 3,
  ARX_RESOURCE_KIND_CINEMATIC = 4,
  ARX_RESOURCE_KIND_AMBIANCE = 5,
};

typedef uint8_t ArxModelPathType;
enum {
  ARX_MODEL_PATH_TYPE_NONE = 0,
  ARX_MODEL_PATH_TYPE_NPC,
  ARX_MODEL_PATH_TYPE_FIX_INTER,
  ARX_MODEL_PATH_TYPE_SYSTEM,
  ARX_MODEL_PATH_TYPE_ARMOR,
  ARX_MODEL_PATH_TYPE_JEWELRY,
  ARX_MODEL_PATH_TYPE_MAGIC,
  ARX_MODEL_PATH_TYPE_MOVABLE,
  ARX_MODEL_PATH_TYPE_PROVISIONS,
  ARX_MODEL_PATH_TYPE_QUEST_ITEM,
  ARX_MODEL_PATH_TYPE_SPECIAL,
  ARX_MODEL_PATH_TYPE_WEAPONS,
  ARX_MODEL_PATH_TYPE_UI_RUNES,
  ARX_MODEL_PATH_TYPE_UI_MENUS,
  ARX_MODEL_PATH_TYPE_EDITOR,
};

typedef uint8_t ArxAnimationPathType;
enum {
  ARX_ANIMATION_PATH_TYPE_NONE = 0,
  ARX_ANIMATION_PATH_TYPE_NPC,
  ARX_ANIMATION_PATH_TYPE_FIX_INTER,
};

typedef uint8_t ArxEntityClassKind;
enum {
  ARX_ENTITY_CLASS_KIND_UNKNOWN = 0,
  ARX_ENTITY_CLASS_KIND_ITEM,
  ARX_ENTITY_CLASS_KIND_NPC,
  ARX_ENTITY_CLASS_KIND_FIX,
  ARX_ENTITY_CLASS_KIND_CAMERA,
  ARX_ENTITY_CLASS_KIND_MARKER,
};

// NOLINTEND(readability-identifier-naming, performance-enum-size)

#endif /* ARX_PISTORIS_PATHS_TYPES_H */
