// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Merxtef

#ifndef ARX_PISTORIS_BASE_ERROR_H
#define ARX_PISTORIS_BASE_ERROR_H

#include "arx_pistoris/base/abi.h"
#include "arx_pistoris/base/indices.h"
#include "arx_pistoris/base/status.h"
#include "arx_pistoris/base/string_view.h"

#include <stddef.h>
#include <stdint.h>

// NOLINTBEGIN(readability-identifier-naming, performance-enum-size)

typedef enum ArxErrorLocationKind {
  ARX_ERROR_LOCATION_NONE = 0,
  ARX_ERROR_LOCATION_LEVEL,
  ARX_ERROR_LOCATION_MODEL,
  ARX_ERROR_LOCATION_ANIMATION,
  ARX_ERROR_LOCATION_AMBIANCE,
  ARX_ERROR_LOCATION_CINEMATIC,
  ARX_ERROR_LOCATION_GLB,
  ARX_ERROR_LOCATION_OBJ,
  ARX_ERROR_LOCATION_JSON,
  ARX_ERROR_LOCATION_AMB,
  ARX_ERROR_LOCATION_CIN,
  ARX_ERROR_LOCATION_DLF,
  ARX_ERROR_LOCATION_FTL,
  ARX_ERROR_LOCATION_FTS,
  ARX_ERROR_LOCATION_LLF,
  ARX_ERROR_LOCATION_TEA,
  ARX_ERROR_LOCATION_AMB_BINARY,
  ARX_ERROR_LOCATION_CIN_BINARY,
  ARX_ERROR_LOCATION_DLF_BINARY,
  ARX_ERROR_LOCATION_FTL_BINARY,
  ARX_ERROR_LOCATION_FTS_BINARY,
  ARX_ERROR_LOCATION_LLF_BINARY,
  ARX_ERROR_LOCATION_TEA_BINARY,
} ArxErrorLocationKind;

typedef enum ArxErrorBinaryRegion {
  ARX_ERROR_BINARY_STORED = 0,
  ARX_ERROR_BINARY_DECODED_PAYLOAD = 1,
} ArxErrorBinaryRegion;

typedef enum ArxErrorElement {
  ARX_ERROR_ELEMENT_NONE = 0,

  ARX_ERROR_ELEMENT_LEVEL_RESOURCE = 0x0100,
  ARX_ERROR_ELEMENT_LEVEL_MINIMAP,
  ARX_ERROR_ELEMENT_LEVEL_LOADING_SCREEN,
  ARX_ERROR_ELEMENT_LEVEL_VERTEX,
  ARX_ERROR_ELEMENT_LEVEL_FACE,
  ARX_ERROR_ELEMENT_LEVEL_TEXTURE,
  ARX_ERROR_ELEMENT_LEVEL_ROOM,
  ARX_ERROR_ELEMENT_LEVEL_PORTAL,
  ARX_ERROR_ELEMENT_LEVEL_ROOM_DISTANCE,
  ARX_ERROR_ELEMENT_LEVEL_NAV_SURFACE_VERTEX,
  ARX_ERROR_ELEMENT_LEVEL_NAV_SURFACE_TRIANGLE,
  ARX_ERROR_ELEMENT_LEVEL_ANCHOR,
  ARX_ERROR_ELEMENT_LEVEL_ANCHOR_CONNECTION,
  ARX_ERROR_ELEMENT_LEVEL_LIGHT,
  ARX_ERROR_ELEMENT_LEVEL_PLAYER_SPAWN,
  ARX_ERROR_ELEMENT_LEVEL_ENTITY,
  ARX_ERROR_ELEMENT_LEVEL_FOG,
  ARX_ERROR_ELEMENT_LEVEL_ZONE,
  ARX_ERROR_ELEMENT_LEVEL_ZONE_PERIMETER_POINT,
  ARX_ERROR_ELEMENT_LEVEL_PATH,
  ARX_ERROR_ELEMENT_LEVEL_PATH_NODE,

  ARX_ERROR_ELEMENT_MODEL_RESOURCE = 0x0200,
  ARX_ERROR_ELEMENT_MODEL_INVENTORY_ICON,
  ARX_ERROR_ELEMENT_MODEL_VERTEX,
  ARX_ERROR_ELEMENT_MODEL_FACE,
  ARX_ERROR_ELEMENT_MODEL_TEXTURE,
  ARX_ERROR_ELEMENT_MODEL_BONE,
  ARX_ERROR_ELEMENT_MODEL_ACTION_POINT,
  ARX_ERROR_ELEMENT_MODEL_SELECTION,

  ARX_ERROR_ELEMENT_ANIMATION_RESOURCE = 0x0300,
  ARX_ERROR_ELEMENT_ANIMATION_KEYFRAME,
  ARX_ERROR_ELEMENT_ANIMATION_GROUP,
  ARX_ERROR_ELEMENT_ANIMATION_GROUP_TRANSFORM,
  ARX_ERROR_ELEMENT_ANIMATION_SOUND,

  ARX_ERROR_ELEMENT_AMBIANCE_RESOURCE = 0x0400,
  ARX_ERROR_ELEMENT_AMBIANCE_TRACK,
  ARX_ERROR_ELEMENT_AMBIANCE_KEY,
  ARX_ERROR_ELEMENT_AMBIANCE_SOUND,

  ARX_ERROR_ELEMENT_CINEMATIC_RESOURCE = 0x0500,
  ARX_ERROR_ELEMENT_CINEMATIC_TIMELINE,
  ARX_ERROR_ELEMENT_CINEMATIC_ILLUSTRATION,
  ARX_ERROR_ELEMENT_CINEMATIC_KEYFRAME,
  ARX_ERROR_ELEMENT_CINEMATIC_TEXTURE,
  ARX_ERROR_ELEMENT_CINEMATIC_SOUND,
  ARX_ERROR_ELEMENT_CINEMATIC_LANGUAGE,
  ARX_ERROR_ELEMENT_CINEMATIC_SOUND_ENCODING,

  ARX_ERROR_ELEMENT_GLB_DOCUMENT = 0x0600,
  ARX_ERROR_ELEMENT_GLB_SCENE,
  ARX_ERROR_ELEMENT_GLB_NODE,
  ARX_ERROR_ELEMENT_GLB_MESH,
  ARX_ERROR_ELEMENT_GLB_PRIMITIVE,
  ARX_ERROR_ELEMENT_GLB_ACCESSOR,
  ARX_ERROR_ELEMENT_GLB_MATERIAL,
  ARX_ERROR_ELEMENT_GLB_TEXTURE,
  ARX_ERROR_ELEMENT_GLB_IMAGE,
  ARX_ERROR_ELEMENT_GLB_SKIN,
  ARX_ERROR_ELEMENT_GLB_ANIMATION,
  ARX_ERROR_ELEMENT_GLB_CHANNEL,
  ARX_ERROR_ELEMENT_GLB_SAMPLER,

  ARX_ERROR_ELEMENT_OBJ_DOCUMENT = 0x0700,
  ARX_ERROR_ELEMENT_OBJ_MATERIAL_LIBRARY,

  ARX_ERROR_ELEMENT_AMB_HEADER = 0x0800,
  ARX_ERROR_ELEMENT_AMB_TRACK,
  ARX_ERROR_ELEMENT_AMB_KEY,
  ARX_ERROR_ELEMENT_AMB_SOUND,

  ARX_ERROR_ELEMENT_CIN_HEADER = 0x0900,
  ARX_ERROR_ELEMENT_CIN_ILLUSTRATION,
  ARX_ERROR_ELEMENT_CIN_KEYFRAME,
  ARX_ERROR_ELEMENT_CIN_SOUND,

  ARX_ERROR_ELEMENT_DLF_HEADER = 0x0A00,
  ARX_ERROR_ELEMENT_DLF_ENTITY,
  ARX_ERROR_ELEMENT_DLF_FOG,
  ARX_ERROR_ELEMENT_DLF_ZONE,
  ARX_ERROR_ELEMENT_DLF_ZONE_POINT,
  ARX_ERROR_ELEMENT_DLF_PATH,
  ARX_ERROR_ELEMENT_DLF_PATH_NODE,

  ARX_ERROR_ELEMENT_FTL_HEADER = 0x0B00,
  ARX_ERROR_ELEMENT_FTL_VERTEX,
  ARX_ERROR_ELEMENT_FTL_FACE,
  ARX_ERROR_ELEMENT_FTL_TEXTURE,
  ARX_ERROR_ELEMENT_FTL_BONE,
  ARX_ERROR_ELEMENT_FTL_ACTION_POINT,
  ARX_ERROR_ELEMENT_FTL_SELECTION,

  ARX_ERROR_ELEMENT_FTS_HEADER = 0x0C00,
  ARX_ERROR_ELEMENT_FTS_CELL,
  ARX_ERROR_ELEMENT_FTS_VERTEX,
  ARX_ERROR_ELEMENT_FTS_FACE,
  ARX_ERROR_ELEMENT_FTS_TEXTURE,
  ARX_ERROR_ELEMENT_FTS_ROOM,
  ARX_ERROR_ELEMENT_FTS_PORTAL,
  ARX_ERROR_ELEMENT_FTS_ROOM_DISTANCE,
  ARX_ERROR_ELEMENT_FTS_ANCHOR,
  ARX_ERROR_ELEMENT_FTS_ANCHOR_CONNECTION,

  ARX_ERROR_ELEMENT_LLF_HEADER = 0x0D00,
  ARX_ERROR_ELEMENT_LLF_LIGHT,
  ARX_ERROR_ELEMENT_LLF_VERTEX_COLOR,

  ARX_ERROR_ELEMENT_TEA_HEADER = 0x0E00,
  ARX_ERROR_ELEMENT_TEA_KEYFRAME,
  ARX_ERROR_ELEMENT_TEA_GROUP_TRANSFORM,
  ARX_ERROR_ELEMENT_TEA_SOUND,
} ArxErrorElement;

typedef struct ArxErrorLocation {
  ArxErrorLocationKind kind;
  ArxErrorElement element;
  ArxStringView element_name;
  size_t input_index;
  size_t index;
  size_t subindex;
  /* Cinematic sound/language identity; sentinel values when unavailable. */
  ArxSoundHandle sound_handle;
  ArxLanguageId language_id;
  size_t line;
  size_t byte_offset;
  size_t requested_bytes;
  ArxErrorBinaryRegion binary_region;
  ArxStringView resource_path;
  ArxStringView label;
  ArxStringView property;
  ArxStringView source_path;
  ArxStringView field;
  ArxStringView json_pointer;
} ArxErrorLocation;

/* Initialize with ARX_ERROR_INIT before first use. String views remain valid until
 * the next operation receiving this object or arx_pistoris_error_clear. Do not copy
 * an initialized object. Clear it before its lifetime ends. */
typedef struct ArxError {
  ArxReturnCode code;
  ArxErrorLocation location;
  ArxStringView detail;
  void* private_data;
} ArxError;

#define ARX_ERROR_LOCATION_INIT \
  {ARX_ERROR_LOCATION_NONE,     \
   ARX_ERROR_ELEMENT_NONE,      \
   {NULL, 0},                   \
   SIZE_MAX,                    \
   SIZE_MAX,                    \
   SIZE_MAX,                    \
   ARX_NO_SOUND_HANDLE,         \
   ARX_INVALID_LANGUAGE_ID,     \
   0,                           \
   SIZE_MAX,                    \
   0,                           \
   ARX_ERROR_BINARY_STORED,     \
   {NULL, 0},                   \
   {NULL, 0},                   \
   {NULL, 0},                   \
   {NULL, 0},                   \
   {NULL, 0},                   \
   {NULL, 0}}
#define ARX_ERROR_INIT {ARX_OK, ARX_ERROR_LOCATION_INIT, {NULL, 0}, NULL}

ARX_EXTERN_C_BEGIN

ARX_API void arx_pistoris_error_clear(ArxError* error) ARX_NOEXCEPT;

ARX_EXTERN_C_END

// NOLINTEND(readability-identifier-naming, performance-enum-size)

#endif /* ARX_PISTORIS_BASE_ERROR_H */
