# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Merxtef

# Regenerate build_info.cpp with the current UTC timestamp
# Usage: cmake -DOUT=<path> -P write_build_info.cmake

if(NOT DEFINED OUT)
    message(FATAL_ERROR "OUT variable required")
endif()

string(TIMESTAMP BUILD_TIME "%Y-%m-%dT%H:%M:%SZ" UTC)

file(WRITE ${OUT} "// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by CMake -- do not edit

namespace pistoris {
const char* buildTime() { return \"${BUILD_TIME}\"; }
}  // namespace pistoris
")
