// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Merxtef

#ifndef ARX_PISTORIS_TYPES_H
#define ARX_PISTORIS_TYPES_H

// NOLINTBEGIN(readability-identifier-naming, performance-enum-size)

#include <stdint.h>

// 0-99 common API and precondition errors
// 100-999 runtime, storage, and internal errors
// 1000-1999 native formats
// 2000-2999 Level
// 3000-3999 Model (reserved)
// 4000-4999 Animation (reserved)
// 5000-5999 Ambiance (reserved)
// 6000-6999 Cinematic (reserved)
// 10000+ external formats
typedef int32_t ArxReturnCode;
enum {
  ARX_OK = 0,
  ARX_INVALID_IDENTIFIER,
  ARX_INVALID_DATA_POINTER,
  ARX_INVALID_HANDLE,
  ARX_INVALID_XFORM,  // det(M) <= 0
  ARX_INVALID_OPTIONS,
  ARX_INDEX_OUT_OF_RANGE,
  ARX_BUFFER_TOO_SMALL,

  ARX_BAD_ALLOC = 100,
  ARX_UNEXPECTED_EOF,
  ARX_INTERNAL_ERROR,
  ARX_COMPRESSION_FAILED,
  ARX_DECOMPRESSION_FAILED,
  ARX_COMPRESSION_INPUT_TOO_LARGE,
  ARX_DECOMPRESSION_LIMIT_EXCEEDED,

  // FTL
  ARX_FTL_BAD_VERSION = 1000,
  ARX_FTL_BAD_OFFSET,
  ARX_FTL_BAD_VERT_N,
  ARX_FTL_BAD_ORIGIN,
  ARX_FTL_BAD_FACE_N,
  ARX_FTL_BAD_FACE_TYPE,
  ARX_FTL_BAD_FACE_VERT_IDX,
  ARX_FTL_BAD_FACE_TEX,
  ARX_FTL_BAD_TEX_N,
  ARX_FTL_BAD_GROUP_N,
  ARX_FTL_BAD_GROUP_IDX_N,
  ARX_FTL_BAD_GROUP_IDX,
  ARX_FTL_BAD_GROUP_ORIGIN,
  ARX_FTL_BAD_ACTION_N,
  ARX_FTL_BAD_ACTION_VERT_IDX,
  ARX_FTL_BAD_SEL_N,
  ARX_FTL_BAD_SEL_IDX_N,
  ARX_FTL_BAD_SEL_IDX,
  ARX_FTL_ORPHAN_BONE,
  ARX_FTL_MULTIPLE_ROOTS,

  // TEA
  ARX_TEA_BAD_VERSION = 1100,
  ARX_TEA_BAD_FRAMES_N,
  ARX_TEA_BAD_GROUPS_N,
  ARX_TEA_BAD_KEYFRAMES_N,
  ARX_TEA_BAD_FLAG_FRAME,
  ARX_TEA_BAD_SAMPLE_SIZE,
  ARX_TEA_NON_MONOTONIC_FRAMES,

  // FTS
  ARX_FTS_BAD_VERSION = 1200,
  ARX_FTS_BAD_METADATA_COUNT,
  ARX_FTS_BAD_GRID_SIZE,
  ARX_FTS_BAD_TEXTURE_COUNT,
  ARX_FTS_BAD_TEXTURE_ID,
  ARX_FTS_DUPLICATE_TEXTURE_ID,
  ARX_FTS_BAD_TEXTURE_PATH,
  ARX_FTS_BAD_POLYGON_COUNT,
  ARX_FTS_BAD_CELL_POLYGON_COUNT,
  ARX_FTS_BAD_CELL_ANCHOR_COUNT,
  ARX_FTS_BAD_POLYGON_TYPE,
  ARX_FTS_BAD_POLYGON_TEXTURE_ID,
  ARX_FTS_BAD_POLYGON_POSITION,
  ARX_FTS_BAD_POLYGON_UV,
  ARX_FTS_BAD_POLYGON_TRANSVAL,
  ARX_FTS_BAD_ANCHOR_COUNT,
  ARX_FTS_BAD_ANCHOR_POSITION,
  ARX_FTS_BAD_ANCHOR_LINK_COUNT,
  ARX_FTS_BAD_ANCHOR_INDEX,
  ARX_FTS_BAD_PORTAL_COUNT,
  ARX_FTS_BAD_ROOM_PORTAL_INDEX,
  ARX_FTS_BAD_PORTAL_ROOM_INDEX,
  ARX_FTS_BAD_PORTAL_TYPE,
  ARX_FTS_BAD_PORTAL_POSITION,
  ARX_FTS_BAD_PORTAL_GEOMETRY,
  ARX_FTS_BAD_ROOM_COUNT,
  ARX_FTS_BAD_ROOM_PORTAL_COUNT,
  ARX_FTS_BAD_ROOM_POLYGON_COUNT,
  ARX_FTS_BAD_ROOM_TEXTURE_VERTEX_COUNT,
  ARX_FTS_BAD_ROOM_POLYGON_INDEX,
  ARX_FTS_BAD_ROOM_DISTANCE_COUNT,
  ARX_FTS_BAD_ROOM_DISTANCE,

  // LLF
  ARX_LLF_BAD_LIGHT_COUNT = 1300,
  ARX_LLF_BAD_BAKED_COLOR_COUNT,
  ARX_LLF_BAD_LIGHT_POSITION,
  ARX_LLF_BAD_LIGHT_COLOR,
  ARX_LLF_BAD_LIGHT_FALLOFF,
  ARX_LLF_BAD_LIGHT_INTENSITY,
  ARX_LLF_BAD_LIGHT_EFFECT,
  ARX_LLF_BAD_LIGHT_FLAGS,
  ARX_LLF_BAD_BAKED_COLOR,

  // DLF
  ARX_DLF_BAD_VERSION = 1400,
  ARX_DLF_BAD_SCENE_COUNT,
  ARX_DLF_BAD_SCENE_PATH,
  ARX_DLF_BAD_PLAYER_SPAWN,
  ARX_DLF_BAD_ENTITY_COUNT,
  ARX_DLF_BAD_ENTITY_CLASS_PATH,
  ARX_DLF_BAD_ENTITY_POSITION,
  ARX_DLF_BAD_ENTITY_ANGLE,
  ARX_DLF_BAD_AI_NODE_COUNT,
  ARX_DLF_BAD_AI_NODE_LINK_COUNT,
  ARX_DLF_BAD_EMBEDDED_LIGHT_COUNT,
  ARX_DLF_BAD_EMBEDDED_COLOR_COUNT,
  ARX_DLF_BAD_FOG_COUNT,
  ARX_DLF_BAD_FOG_POSITION,
  ARX_DLF_BAD_FOG_COLOR,
  ARX_DLF_BAD_FOG_ANGLE,
  ARX_DLF_BAD_FOG_EFFECT,
  ARX_DLF_BAD_PATH_RECORD_COUNT,
  ARX_DLF_BAD_PATH_NODE_COUNT,
  ARX_DLF_BAD_ZONE_NAME,
  ARX_DLF_BAD_ZONE_POSITION,
  ARX_DLF_BAD_ZONE_POINT_COUNT,
  ARX_DLF_BAD_ZONE_POINT,
  ARX_DLF_BAD_ZONE_HEIGHT,
  ARX_DLF_BAD_ZONE_COLOR,
  ARX_DLF_BAD_ZONE_FARCLIP,
  ARX_DLF_BAD_ZONE_AMBIANCE,
  ARX_DLF_BAD_PATH_NAME,
  ARX_DLF_BAD_PATH_POSITION,
  ARX_DLF_BAD_PATH_NODE_POSITION,
  ARX_DLF_BAD_PATH_NODE_TYPE,
  ARX_DLF_BAD_PATH_FIRST_NODE,

  // Level geometry
  ARX_LEVEL_NO_GEOMETRY = 2000,
  ARX_LEVEL_TOO_MANY_VERTICES,
  ARX_LEVEL_BAD_VERTEX_POSITION,
  ARX_LEVEL_VERTEX_OUT_OF_BOUNDS,
  ARX_LEVEL_TOO_MANY_TEXTURES,
  ARX_LEVEL_BAD_TEXTURE_PATH,
  ARX_LEVEL_BAD_TEXTURE_IMAGE,
  ARX_LEVEL_TOO_MANY_FACES,
  ARX_LEVEL_BAD_FACE_VERTEX,
  ARX_LEVEL_BAD_FACE_TEXTURE,
  ARX_LEVEL_BAD_FACE_TYPE,
  ARX_LEVEL_BAD_FACE_NORMAL,
  ARX_LEVEL_BAD_FACE_UV,
  ARX_LEVEL_BAD_FACE_TRANSVAL,
  ARX_LEVEL_DEGENERATE_FACE,
  ARX_LEVEL_BAD_VERTEX_WELD_SEGMENT,
  ARX_LEVEL_OVERLAPPING_VERTEX_WELD_SEGMENTS,

  // Level rooms
  ARX_LEVEL_NO_ROOMS = 2100,
  ARX_LEVEL_TOO_MANY_ROOMS,
  ARX_LEVEL_BAD_ROOM_NAME,
  ARX_LEVEL_DUPLICATE_ROOM_NAME,
  ARX_LEVEL_BAD_FACE_ROOM_COUNT,
  ARX_LEVEL_BAD_FACE_ROOM_INDEX,
  ARX_LEVEL_BAD_ROOM_DISTANCE_COUNT,
  ARX_LEVEL_BAD_ROOM_DISTANCE,
  ARX_LEVEL_TOO_MANY_PORTALS,
  ARX_LEVEL_BAD_PORTAL_NAME,
  ARX_LEVEL_DUPLICATE_PORTAL_NAME,
  ARX_LEVEL_BAD_PORTAL_ROOM,
  ARX_LEVEL_BAD_PORTAL_SHAPE,
  ARX_LEVEL_BAD_PORTAL_VERTEX,
  ARX_LEVEL_PORTAL_OUT_OF_BOUNDS,
  ARX_LEVEL_DEGENERATE_PORTAL,
  ARX_LEVEL_NON_PLANAR_PORTAL,
  ARX_LEVEL_INCONSISTENT_PORTAL_ORIENTATION,
  ARX_LEVEL_SELF_INTERSECTING_PORTAL,

  // Level navigation
  ARX_LEVEL_BAD_NAV_SURFACE = 2200,
  ARX_LEVEL_TOO_MANY_NAV_SURFACE_VERTICES,
  ARX_LEVEL_BAD_NAV_SURFACE_VERTEX,
  ARX_LEVEL_BAD_NAV_SURFACE_TRIANGLE,
  ARX_LEVEL_DEGENERATE_NAV_SURFACE_TRIANGLE,
  ARX_LEVEL_NAV_SURFACE_REQUIRED,
  ARX_LEVEL_EMPTY_NAVIGATION_RESULT,
  ARX_LEVEL_TOO_MANY_ANCHORS,
  ARX_LEVEL_BAD_ANCHOR_NAME,
  ARX_LEVEL_DUPLICATE_ANCHOR_NAME,
  ARX_LEVEL_BAD_ANCHOR_POSITION,
  ARX_LEVEL_BAD_ANCHOR_RADIUS,
  ARX_LEVEL_BAD_ANCHOR_HEIGHT,
  ARX_LEVEL_BAD_ANCHOR_FLAGS,
  ARX_LEVEL_ANCHOR_OUT_OF_BOUNDS,
  ARX_LEVEL_TOO_MANY_ANCHOR_CONNECTIONS,
  ARX_LEVEL_BAD_ANCHOR_CONNECTION_INDEX,
  ARX_LEVEL_BAD_ANCHOR_CONNECTION_ORDER,

  // Level lighting
  ARX_LEVEL_TOO_MANY_LIGHTS = 2300,
  ARX_LEVEL_BAD_LIGHT_NAME,
  ARX_LEVEL_DUPLICATE_LIGHT_NAME,
  ARX_LEVEL_BAD_LIGHT_POSITION,
  ARX_LEVEL_BAD_LIGHT_COLOR,
  ARX_LEVEL_BAD_LIGHT_FALLOFF,
  ARX_LEVEL_BAD_LIGHT_INTENSITY,
  ARX_LEVEL_BAD_LIGHT_EFFECT,
  ARX_LEVEL_BAD_LIGHT_FLAGS,
  ARX_LEVEL_BAD_CORNER_COLOR_COUNT,
  ARX_LEVEL_BAD_CORNER_COLOR,

  // Level scene
  ARX_LEVEL_BAD_PLAYER_SPAWN = 2400,
  ARX_LEVEL_TOO_MANY_ENTITIES,
  ARX_LEVEL_BAD_ENTITY_NAME,
  ARX_LEVEL_DUPLICATE_ENTITY_NAME,
  ARX_LEVEL_BAD_ENTITY_CLASS_PATH,
  ARX_LEVEL_BAD_ENTITY_POSITION,
  ARX_LEVEL_BAD_ENTITY_ROTATION,
  ARX_LEVEL_TOO_MANY_FOGS,
  ARX_LEVEL_BAD_FOG_NAME,
  ARX_LEVEL_DUPLICATE_FOG_NAME,
  ARX_LEVEL_BAD_FOG_POSITION,
  ARX_LEVEL_BAD_FOG_ROTATION,
  ARX_LEVEL_BAD_FOG_COLOR,
  ARX_LEVEL_BAD_FOG_EFFECT,
  ARX_LEVEL_TOO_MANY_ZONES,
  ARX_LEVEL_BAD_ZONE_NAME,
  ARX_LEVEL_DUPLICATE_ZONE_NAME,
  ARX_LEVEL_BAD_ZONE_PERIMETER,
  ARX_LEVEL_BAD_ZONE_HEIGHT_MODE,
  ARX_LEVEL_BAD_ZONE_HEIGHT,
  ARX_LEVEL_BAD_ZONE_COLOR,
  ARX_LEVEL_BAD_ZONE_FARCLIP,
  ARX_LEVEL_BAD_ZONE_AMBIANCE,
  ARX_LEVEL_TOO_MANY_PATHS,
  ARX_LEVEL_BAD_PATH_NAME,
  ARX_LEVEL_DUPLICATE_PATH_NAME,
  ARX_LEVEL_BAD_PATH_POSITION,
  ARX_LEVEL_BAD_PATH_NODE_COUNT,
  ARX_LEVEL_BAD_PATH_NODE_POSITION,
  ARX_LEVEL_BAD_PATH_NODE_TYPE,
  ARX_LEVEL_BAD_PATH_FIRST_NODE,

  // OBJ
  ARX_OBJ_BAD_FORMAT = 10000,
  ARX_OBJ_BAD_VERTEX_IDX,
  ARX_OBJ_TOO_MANY_VERTICES,
  ARX_OBJ_TOO_MANY_NORMALS,
  ARX_OBJ_TOO_MANY_TEXCOORDS,
  ARX_OBJ_TOO_MANY_TEXTURES,
  ARX_OBJ_TOO_MANY_MATERIALS,
  ARX_OBJ_TOO_MANY_FACES,
  ARX_OBJ_NO_GEOMETRY,

  // GLB common
  ARX_GLB_BAD_FORMAT = 11000,
  ARX_GLB_UNSUPPORTED_FEATURE,
  ARX_GLB_AMBIGUOUS_SCENE,

  // GLB Level
  ARX_GLB_NO_LEVEL_GEOMETRY = 11100,
  ARX_GLB_BAD_LEVEL_GEOMETRY,
  ARX_GLB_BAD_LEVEL_MATERIAL,
  ARX_GLB_BAD_LEVEL_MATERIAL_RESERVED_STEM,
  ARX_GLB_BAD_LEVEL_MATERIAL_STEM_COLLISION,
  ARX_GLB_BAD_LEVEL_HIERARCHY,
  ARX_GLB_BAD_LEVEL_ROOM,
  ARX_GLB_BAD_LEVEL_PORTAL,
  ARX_GLB_BAD_LEVEL_NAV_SURFACE,
  ARX_GLB_BAD_LEVEL_ANCHOR,
  ARX_GLB_BAD_LEVEL_PLAYER_SPAWN,
  ARX_GLB_BAD_LEVEL_ENTITY,
  ARX_GLB_BAD_LEVEL_FOG,
  ARX_GLB_BAD_LEVEL_ZONE,
  ARX_GLB_BAD_LEVEL_PATH,
  ARX_GLB_BAD_LEVEL_LIGHT,

  // GLB Model
  ARX_GLB_MODEL_TOO_MANY_VERTICES = 11200,
  ARX_GLB_MODEL_NON_UNIFORM_SCALE,  // or shear
  ARX_GLB_MODEL_MULTIPLE_SKINS,     // disconnected armatures

  // GLB Animation
  ARX_GLB_ANIMATION_GROUP_MISMATCH = 11300,
  ARX_GLB_ANIMATION_NO_MODEL_GROUPS,

  // JSON
  ARX_JSON_BAD_FORMAT = 12000,
  ARX_JSON_BAD_SCHEMA,
  ARX_JSON_LIMIT_EXCEEDED
};

typedef int32_t ArxLogLevel;
enum { ARX_LOG_DEBUG = 0, ARX_LOG_INFO = 1, ARX_LOG_WARN = 2, ARX_LOG_ERROR = 3 };

// fn = NULL disables logging (default)
typedef void (*ArxLogFn)(ArxLogLevel level, const char* msg, void* userdata);

// NOLINTEND(readability-identifier-naming, performance-enum-size)

#endif /*ARX_PISTORIS_TYPES_H*/
