# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Merxtef

add_subdirectory(src)

set(ARX_PISTORIS_INTERNAL_TARGETS ${ARX_PISTORIS_INTERNAL_TARGETS} PARENT_SCOPE)
set(ARX_PISTORIS_INTERNAL_DEPENDENCIES ${ARX_PISTORIS_INTERNAL_DEPENDENCIES} PARENT_SCOPE)
set(ARX_PISTORIS_C_LIBRARY_SOURCES ${ARX_PISTORIS_C_LIBRARY_SOURCES} PARENT_SCOPE)
